#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
cd "$(dirname "$0")/.."   # repo root, so .env and supabase/ resolve

banner "chef-gpt · Supabase + Claude Desktop setup"

# ── 1. CLI ────────────────────────────────────────────────────────────────
stage "Supabase CLI: install and log in"
if command -v supabase >/dev/null 2>&1; then
  say "Supabase CLI found: $(supabase --version)"
else
  say "Installing the Supabase CLI with Homebrew."
  brew install supabase/tap/supabase
fi
say "Logging in opens a browser; approve the token there."
supabase login
if [[ ! -f supabase/config.toml ]]; then
  say "Creating supabase/config.toml (answer N to VS Code settings)."
  supabase init
fi

# ── 2. Org ────────────────────────────────────────────────────────────────
stage "Pick the organisation"
say "Your organisations:"
supabase orgs list
step "Copy the ID of the org that should own chef-gpt (the one whose dashboard URL you already use)."
ask SUPABASE_ORG_ID "Org ID:"
write_env SUPABASE_ORG_ID "$SUPABASE_ORG_ID"

# ── 3. Dev project ────────────────────────────────────────────────────────
stage "Create the dev project (chef-gpt-dev)"
say "This is the project Claude Desktop connects to while developing."
ask SUPABASE_REGION "Region (e.g. eu-central-1, eu-north-1):"
write_env SUPABASE_REGION "$SUPABASE_REGION"
ask_secret SUPABASE_DEV_DB_PASSWORD "Choose a database password for chef-gpt-dev:"
if [[ -n "$(_existing SUPABASE_DEV_PROJECT_REF || true)" ]]; then
  note "SUPABASE_DEV_PROJECT_REF already in .env; skipping create."
  SUPABASE_DEV_PROJECT_REF=$(_existing SUPABASE_DEV_PROJECT_REF)
else
  supabase projects create chef-gpt-dev --org-id "$SUPABASE_ORG_ID" --region "$SUPABASE_REGION" --db-password "$SUPABASE_DEV_DB_PASSWORD"
  say "Projects now:"
  supabase projects list
  step "Copy the REFERENCE ID of chef-gpt-dev from the list above."
  ask SUPABASE_DEV_PROJECT_REF "chef-gpt-dev project ref:"
fi
write_env SUPABASE_DEV_DB_PASSWORD "$SUPABASE_DEV_DB_PASSWORD"
write_env SUPABASE_DEV_PROJECT_REF "$SUPABASE_DEV_PROJECT_REF"
say "Linking this repo to chef-gpt-dev and fetching its API keys."
supabase link --project-ref "$SUPABASE_DEV_PROJECT_REF" --password "$SUPABASE_DEV_DB_PASSWORD"
supabase projects api-keys --project-ref "$SUPABASE_DEV_PROJECT_REF"
step "From the table above copy the 'anon' (or publishable) key and the 'service_role' (or secret) key."
ask SUPABASE_ANON_KEY "anon / publishable key:"
ask_secret SUPABASE_SERVICE_ROLE_KEY "service_role / secret key:"
write_env SUPABASE_URL "https://${SUPABASE_DEV_PROJECT_REF}.supabase.co"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
write_env MCP_URL "https://${SUPABASE_DEV_PROJECT_REF}.supabase.co/functions/v1/chef/mcp"
if ! grep -q '^\[functions.chef\]' supabase/config.toml 2>/dev/null; then
  printf '\n[functions.chef]\nverify_jwt = false\n' >> supabase/config.toml
  say "Added [functions.chef] verify_jwt = false to supabase/config.toml (the server verifies tokens itself)."
fi

# ── 4. Prod project (optional now) ────────────────────────────────────────
stage "Create the prod project (chef-gpt) — optional for now"
say "Friends connect to this one. You can skip it until Phase 7."
if confirm "Create chef-gpt (prod) now?"; then
  ask_secret SUPABASE_PROD_DB_PASSWORD "Choose a database password for chef-gpt:"
  supabase projects create chef-gpt --org-id "$SUPABASE_ORG_ID" --region "$SUPABASE_REGION" --db-password "$SUPABASE_PROD_DB_PASSWORD"
  supabase projects list
  step "Copy the REFERENCE ID of chef-gpt."
  ask SUPABASE_PROD_PROJECT_REF "chef-gpt project ref:"
  write_env SUPABASE_PROD_DB_PASSWORD "$SUPABASE_PROD_DB_PASSWORD"
  write_env SUPABASE_PROD_PROJECT_REF "$SUPABASE_PROD_PROJECT_REF"
else
  SKIPPED+=("prod project chef-gpt (re-run this wizard later)")
fi

# ── 5. OAuth 2.1 server ───────────────────────────────────────────────────
stage "Enable Supabase Auth as OAuth 2.1 server (dev)"
say "Claude Desktop registers itself as an OAuth client dynamically, so DCR must be on."
say "The sign-in/consent page is a static site on GitHub Pages (Supabase will not serve HTML itself)."
ask SITE_URL "Public URL of the auth site (e.g. https://<github-user>.github.io/chef-gpt):"
SITE_URL="${SITE_URL%/}"
write_env SITE_URL "$SITE_URL"
open_url "https://supabase.com/dashboard/project/${SUPABASE_DEV_PROJECT_REF}/auth/url-configuration"
step "Set Site URL to:   ${SITE_URL}"
step "Under Redirect URLs add:   ${SITE_URL}/"
note "Google and magic-link sign-ins return to the auth site; Supabase refuses redirects that are not listed."
step "Save."
pause "Done? Press Enter."
open_url "https://supabase.com/dashboard/project/${SUPABASE_DEV_PROJECT_REF}/auth/oauth-server"
note "If that URL 404s, go to the project → Authentication → OAuth Server."
step "Turn ON 'Enable OAuth Server'."
step "Turn ON 'Allow Dynamic OAuth Apps' (dynamic client registration)."
step "Set 'Authorization Path' to:   /"
step "The preview must read:   ${SITE_URL}/"
step "Save changes."
pause "Done? Press Enter."

# ── 6. Google OAuth client ────────────────────────────────────────────────
stage "Google: create an OAuth client for sign-in"
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick (or create) a Google Cloud project for chef-gpt."
step "If asked, configure the OAuth consent screen first: External, app name 'chef-gpt', your email, save."
step "Create credentials → OAuth client ID → Application type: Web application, name 'chef-gpt-dev'."
step "Authorized redirect URI — add exactly:"
say "    https://${SUPABASE_DEV_PROJECT_REF}.supabase.co/auth/v1/callback"
step "Create, then copy the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Google client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── 7. Supabase providers ─────────────────────────────────────────────────
stage "Supabase: enable Google + magic link (dev)"
open_url "https://supabase.com/dashboard/project/${SUPABASE_DEV_PROJECT_REF}/auth/providers"
step "Google → enable → paste the Client ID and Client secret from the previous stage → Save."
step "Email → make sure it is enabled (magic links use it). Leave 'Confirm email' as you like."
pause "Done? Press Enter."

# ── 8. Claude Code plugin ─────────────────────────────────────────────────
stage "Claude Code: install the MCP Apps plugin"
say "These are Claude Code slash commands; run them in your Claude Code session, not here:"
say ""
say "    /plugin marketplace add modelcontextprotocol/ext-apps"
say "    /plugin install mcp-apps@modelcontextprotocol-ext-apps"
say ""
note "They add the create-mcp-app / add-app-to-server skills used when building the four views."
pause "Done (or noted for later)? Press Enter."

finish
say "Next: Spike B — deploy the hello view with OAuth and add it as a custom connector in Claude Desktop."
say "    deno task stage:edge && supabase functions deploy chef --project-ref ${SUPABASE_DEV_PROJECT_REF} --no-verify-jwt"
